export const CREAT_PAYMENT_INTENT_START = "CREAT_PAYMENT_INTENT_START";
export const CREAT_PAYMENT_INTENT_SUCCESS = "CREAT_PAYMENT_INTENT_SUCCESS";
export const CREAT_PAYMENT_INTENT_FAILURE = "CREAT_PAYMENT_INTENT_FAILURE";
export const RESET_FETCHING_STATUS = "RESET_PAYMENT_INTENT_STATUS";
export const RESET_CHECKOUT_STATE = "RESET_CHECKOUT_STATE";
