export const CREAT_PAYMENT_INTENT_START = "CREAT_PAYMENT_INTENT_START";
export const CREAT_PAYMENT_INTENT_SUCCESS = "CREAT_PAYMENT_INTENT_SUCCESS";
export const CREAT_PAYMENT_INTENT_FAILURE = "CREAT_PAYMENT_INTENT_FAILURE";
